### ISSUE TITLE
problems recompiling with mglMake(1,'eyelink') for OSX 10.10.x

### ISSUE THREAD

**Issue by schluppeck** [justingardner/mgl#11]
found a couple of small things in trying to recompile MGL for OSX 10.10.5 - but all easily fixable:
1. major / minor version numbers
   the numeric version of "10.10" (line 129 onwards in `mglMake()` causes problem. I think a better way (than parsing for float) would be to check for numbers like this `sscanf('10.10.5','%i.%i.%i')`
2. otherwise compiling with the flags used for 10.9 also works fine for 10.10 in my hands.
   `optf = '-Dchar16_t=uint16_T';` is good.
3. the only wobbly the compiler throws is for `mglPrivateEyelinkSetup()` where the cocoa-version of a function returns VOID... but should return an INT. What's a reasonable return value here? Not sure

`INT16 mglcGetKeyEvent(MGLKeyEvent *mglKey)`

I tried with 
`return 0; // ds` and it compiles fine.

Will test w/ eyetracker here early next week... hope things are good in NoCal ;]

**Comment by justingardner** [comment]
Closing this out - we are working on a new version of mgl (based on metal) with new compilation scripts mglMakeMetal

**Comment by schluppeck** [comment]
... saw some of the commits. Very cool that you are taking this on (it's like Cupertino thinks you are not busy enough as is 😬)
