### ISSUE TITLE
mglEditScreenParams - responseKeys

### ISSUE THREAD

**Issue by dbirman** [justingardner/mgl#2]
on marple I use the 1/2/8/9/0 keys as response keys. Currently the responseKeys list is set to '1 2 3 4 5 6 7 8 9 0'. Interestingly if you set it to '1 2 8 9 0', it stops picking up the responses to the 8/9/0 keys.

**Comment by justingardner** [comment]
When you set to '1 2 8 9 0' it should be mapping these responses to 1-5 (which may not be what you were expecting) - the idea is that if you set to something like 'a s' you would still get response 1 and response 2. Can you check to see if that is working properly (again it seems to be working properly with taskTemplate) and if so, find a place in the wiki to document this in a way that won't confuse others in the future?

**Comment by dbirman** [comment]
Edited wiki to reflect this
