### ISSUE TITLE
Namespace conflict with routine "isfile" in 2018a

### ISSUE THREAD

**Issue by DavidBrainard** [justingardner/mgl#27]
Matlab 2018a has a built-in called "isfile".  When you add mgl to the path, it produces a warning that mgl does too.  And, it's true.  Easy fix is probably to rename mgl's isfile and make the corresponding change in places that call it.

**Comment by justingardner** [comment]
<sigh> only took Mathworks 15 years to code this up. Sounds like it should function the same as my helper/util. Could probably just remove my isfile.m on Matlab2018a?

**Comment by justingardner** [comment]
Renamed to mglIsFile
