### ISSUE TITLE
mglEditScreenParams - saveData

### ISSUE THREAD

**Issue by dbirman** [justingardner/mgl#3]
on marple the saveData flag is set to '1', which seems to imply that it auto-saves all data. But it just asks you whether you want to save (the functionality for 'saveData=-1').

**Comment by justingardner** [comment]
I am having trouble recreating this on my laptop or marble. Does your stimulus program have my screen.saveData set someplace before initScreen (an older override style). Does it not save properly if you run a vanilla program like taskTemplate?

**Comment by dbirman** [comment]
Same problem on marble still: if I call taskTemplate, let it run a bit, then hit esc, I get:

Save data ~/data/taskTemplate/s300/150119_stim13? (y/n) 

Not setting myscreen.saveData. Did you recreate it on marble using the vpixx as the external screen? If not that could explain why you didn't see the problem.

**Comment by dbirman** [comment]
Justin fixed: https://github.com/justingardner/mgl/commit/69c1aa14ad6d955aab703caa9024506b8afff1f9
