### ISSUE TITLE
Resources to run mgl on Linux (Fedora)?

### ISSUE THREAD

**Issue by aernesto** [justingardner/mgl#30]
Hi,

according to [this page](http://www.pc.rhul.ac.uk/staff/J.Larsson/dokuwiki/doku.php?id=software:mgl:mglsinglepage), mgl may be compiled and run under Linux. However, I was unable to find resources (like a step-by-step guide) on how to do this.

Could you point me to such resources if they exist, please, and if not, could you give me at least basic instructions on how to proceed? I am happy to write a Wiki reporting my own steps, if I succeed.

Also, if this is not the right place for this post, please let me know where I should post it.

Best, 

Adrian

**Comment by justingardner** [comment]
I'm afraid not. You might try to contact Jonas Larsson directly who had written the linux code. Most of the mgl code is written with OpenGL calls that are OS independent, but things like opening and closing an OpenGL screen and setting the gamma table are OS specific. The existing linux code in the mgl repo probably would need to be tinkered with to get it working again...

**Comment by aernesto** [comment]
Thank you very much. I will try to contact him.
