### ISSUE TITLE
`mglPrivateVolume.mexmaci64` not in repo anymore

### ISSUE THREAD

**Issue by schluppeck** [justingardner/mgl#32]
`mglPrivateVolume.mexmaci64` is not in repo anymore. Could a `mexmaci64` version be included again?

Came across this after `git clone` on a new machine (in labs, where we are forced to use latest Matlab version R2018a, because of the way licenses are served at our institutions - ugh!). 

``mglMake()`` doesn't work on recent macOS/Matlab combos (cupertino + natick!), but apart from fullscreen windows everything else I have tried is seems to be running ok w/ previously compiled mex files... e.g. working on code / demos with `screenNum=0`

Best from over here
Denis

**Comment by justingardner** [comment]
Weird. I added it back. 

I haven't updated Matlab in some time now, but have plans to look at compatibility soonish ;)
