### ISSUE TITLE
mgldigio doesn't work in recent  with 64bit matlabs?

### ISSUE THREAD

**Issue by iPsych** [justingardner/mgl#35]
Hello, mgldigio compilation repeatedly failed in High Sierra with Matlab 2017 and 2019.
As far as I know, NIDaqMX Base supports 64bit in v14 and v15.
However, it always stops with the error "Undefined symbols for architecture x86_64".
Does the code is non-usable or can be used with some additional lines?

**Comment by justingardner** [comment]
Closing out - we are working on a new version of metal (based on metal) with new compilation scripts mglMakeMetal this will be the new default version of mgl for newer systems / matlab versions / OS versions
