### ISSUE TITLE
Support 1D textures

### ISSUE THREAD

**Issue by benjamin-heasly** [justingardner/mgl#37]
MGL v2 with OpenGL supported 1D textures.  Currently MGL createTexture only expects 2D textures with RGBA element values.

There is a concept of 1D texture in Metal: https://developer.apple.com/documentation/metal/mtltexturetype/type1d
I'm not sure if it's the same thing we want.

Either way, we ought to be able to support this concept -- perhaps by creating 1xn textures with equal RGB values, and perhaps choosing UV coordinates cleverly when we blt them

**Comment by justingardner** [comment]
This appears to be working now
