### ISSUE TITLE
Support uint textures

### ISSUE THREAD

**Issue by benjamin-heasly** [justingardner/mgl#38]
Currently in MGL with Metal, we only support RGBA float textures.  These are pretty deep, 16 bytes per texture element!

We probably want to support uint textures as well, with 3 or 4 bytes per element.

I wonder if these two formats are enough -- shallow and deep.  It would be nice to keep it simple, since each new pixel format we support adds cases to the socket commands as well as the Metal rendering pipeline setup -- especially when rendering from one texture as a blt source, to another texture as a rendering target.

**Comment by justingardner** [comment]
Mostly seems a matter of speed, I think we should revisit on another block to think about how to support very rapid, frame-accurate displays - people who would want speed, may want to go all the way to the metal, if you will, and have some way to change textures on the graphics card end to insure highly speed efficient ways of, say, creating random white-noise displays.

**Comment by justingardner** [comment]
Closing this - if we need faster create/blt speeds we can revisit.
