### ISSUE TITLE
Can we deprecate mglTextDraw and replace with utils to update an existing texture?

### ISSUE THREAD

**Issue by benjamin-heasly** [justingardner/mgl#39]
In MGL v2, mglTextDraw would create a new image array, create a new OpenGL texture with this image, blt this texture, then delete this texture.

I'm not sure if this will be a good fit for v3 with Metal.  Since we're sending texture data over the socket, we might want to be more strict about creating and managing texture resources before drawing, and then just blt-ing textures while drawing each frame.

A possible alternative would be to create a texture ahead of time, to hold the text.  Then on each frame that we want to update the texture, use mglUpdateTexture to send over new image contents, and then blt the texture.  We'd still be sending lots of image data per frame, but we could have the Metal texture to hold the data allocated ahead of time.

**Comment by justingardner** [comment]
What did you have in mind for this? I think the functionality of the call is useful and simple - can we just change the back-end of how it is implemented?

**Comment by benjamin-heasly** [comment]
In performance-sensitive code, I think we'll still want to create and delete textures outside of the draw loop.  We can use mglUpdateTexture to update a texture's buffer contents during the loop.  This is demoed in mglTestUpdateTexture.
