### ISSUE TITLE
Typos from mglMetal Bug Hunt 

### ISSUE THREAD

**Issue by cjoynes** [justingardner/mgl#44]
mglOpen (line 36): ‘fprinft’ should be ‘fprintf’ 

mglTextDraw (line 44): ‘textTexture’ should be ‘tex’

mglClearScreen and mglFlush print some numbers to the terminal (probably because some line doesn’t have a semicolon at the end)

dispPercent goes from -inf to inf rather than 0 to 1

**Comment by justingardner** [comment]
Fixed these - the numbers are the ack, processedTime, so are expected behavior
