### ISSUE TITLE
BugHunt: mglRenderingDemo Issues 

### ISSUE THREAD

**Issue by cjoynes** [justingardner/mgl#45]
- mglRenderingDemo # 3 (mglTestDots): error `Index in position 3 exceeds array bounds. Error in mglRunRenderingTests (line 53)
         imshow(result.renderedImage(:,:,1:3));` Rendered image is not being captured in the non-interactive mode for some tests (Matlab 2020a)

- mglRenderingDemo # 14 does not appear to produce the correct output, no red squares appear "on top" of green ones
 
- mglRenderingDemo # 18 (mglTestText) returns the error `Output argument "tex" (and maybe others) not assigned during call to "mglText"` (Matlab 2018b & 2021); others said this test just shows a black screen 

- If the window is not full screen mglRenderingDemo is unable to close the window to proceed to next test. **Temporary Solution:** ctrl+c to kill process and move on to next test

**Comment by benjamin-heasly** [comment]
On Gardner lab Lagavulin machine, I found the issue with mglTestDots and mglTestText.  Some of the new tests I made for the automated test runner (mglRunRenderingTests) had the same names as existing mgl tests.  So there was Matlab path shadowing.  On my machine this happened to work in favor of the new tests.  But not on Lagavulin.  I renamed the new tests to not conflict, and that should clear up those two.

**Comment by justingardner** [comment]
Closing. This seems to be mostly working now. mglTestDots was modified because you now specify the argument as size of dots in degrees. MglTestText seems to plot the text flipped upside down. Will look into that, but these demos are basically working fine now, so closing.
