### ISSUE TITLE
Bug Hunt: Backwards Compatibility Issue 

### ISSUE THREAD

**Issue by cjoynes** [justingardner/mgl#46]
mglCreateTexture requires dimX x dimY x 4 images and doesn't take 4 x dimX x dimY (so old code might not work in Metal)

**Comment by justingardner** [comment]
This is for uint8 textures only, I believe. I added a check in mglCreateTexture to convert and should be working now. We may need to revisit this because the intention was to have uint8 textures be in the device format for fast transfer and display.
