### ISSUE TITLE
Bug Hunt: mglTest Issues 

### ISSUE THREAD

**Issue by cjoynes** [justingardner/mgl#47]
All issue found in 2021b
- mglTestAlignment: unrecognized function or variable 'textTexture'  

```
Error in mglTextDraw (line 44)
mglDeleteTexture(textTexture);
Error in mglTestAlignment (line 27)
mglTextDraw('Visual angle coordinates',[0 1]);
```

- mglTestGamma: slidebar doesn't update gamma value 
- mglTestStencil: crashes Matlab 
- mglTestTexMulti: mgl window doesn’t show anything but the code prints out bunch of numbers (I guess some lines are printing out the number in mglSocketWrite code)
- mglTestText: Doesn't print out anything on the mgl window and also stopped to respond

**Comment by benjamin-heasly** [comment]
I think these are resolved now, but I'll leave open until we can retest.

**Comment by justingardner** [comment]
These seem basically resolved. So I will close, but mglTestStencil only draws the inner points - need to check on that. And mglTestText shows text flipped. Will open separate issues to track those.
