### ISSUE TITLE
Stencils

### ISSUE THREAD

**Issue by justingardner** [justingardner/mgl#51]
Stencils need to be implemented - and test program mglTestStencil should work

**Comment by benjamin-heasly** [comment]
I started looking into this.  So far, it looks like Metal directly supports stencils that are similar to OpenGL, with a similar API and set of concepts.

- https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glStencilFunc.xhtml
- https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glStencilOp.xhtml
- https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Render-Ctx/Render-Ctx.html#//apple_ref/doc/uid/TP40014221-CH7-SW38

I'm still unclear if we need to manage our own textures to act as the stencil write targets.  We did need to manage our own texture for the depth test -- so probably also for other stencils...

**Comment by justingardner** [comment]
Great! Looks like it is working as expected. I will close out.

**Comment by justingardner** [comment]
Actually, sorry, but when I got the computer to run mgl by opening up gatekeeper it crashes on mglTestStencil. Maybe a binary compatibility issue? Can you login and check? The computer name is balvenie...

**Comment by justingardner** [comment]
This is duplicated with the other issue, and no longer crashes. So will close
