### ISSUE TITLE
frameRate and bitDepth settings

### ISSUE THREAD

**Issue by justingardner** [justingardner/mgl#53]
In mglOpen you commented out frameRate and bitDepth configuration. Why? This is set by mglResolution which hasn't change in metal, no? These are important settings - particularly frameRate that should still be settable.

**Comment by benjamin-heasly** [comment]
Is there a one-line change to allow specifying the bit depth of our metal view and/or frame buffer?

**Comment by benjamin-heasly** [comment]
Oh I see, I added a warning that these params are unsupported.  I think I misunderstood how they worked.  I removed the warning now.

**Comment by benjamin-heasly** [comment]
70c53cea2d5dd4b3b1aacdb7c8312c5e021a8ec5 also adds an experimental command to set the color pixel format of the mglMetal app's view -- mglMetalSetViewColorPixelFormat
