### ISSUE TITLE
mglMetal doesn't open a screen

### ISSUE THREAD

**Issue by jiwonyeon** [justingardner/mgl#58]
The machine I've tested is on Monterey 12.3.1 (iMac; Balvanie). When I downloaded mglMetal and tried to open a screen, the computer recognized MGL as malicious software and did not open a screen. Basically it seems. like it recognized all files with "mexmaci.64" extension as malicious, and even though I asked it to open it anyway it failed to open since there are multiple files with the same extension. I'm attaching an example screen shot of the issue.

<img width="252" alt="Screen Shot 2022-05-09 at 5 41 11 PM" src="https://user-images.githubusercontent.com/55372429/167520858-7bf27c47-f07c-4214-8ec6-6f409196bcdd.png">

**Comment by justingardner** [comment]
Seems to work by disabling gate-keeper. Though this is probably not super-ideal either. Ben, can you sign the mglMetal app and compiled functions using XCode: https://developer.apple.com/developer-id/ (might still need to get them "notarized", but this seems like a step we may need to do to avoid this issue...

**Comment by justingardner** [comment]
Closing this as it hasn't been happening recently, so seems resolved if you use git clone to get the repo.
