### ISSUE TITLE
mglLines2 - cannot change size in mgl metal

### ISSUE THREAD

**Issue by jenhaensel** [justingardner/mgl#59]
When using the function mglLines2 in mgl metal (running on Big Sur 11.3.1, Matlab vR2021a), the resulting lines remain the same size no matter which value is specified for the 'size' parameter (e.g., 1, 5, and 20 all result in the same size).

**Comment by benjamin-heasly** [comment]
Hi, thanks, I can see this as well.

My understanding is that line width is not directly supported as a part of the Metal API for line primitives.  So in 7b5e4a5fb6ba904c96f50a36ed13c97429b88815 I created a new function, mglMetalLines which draws wide lines as quads.  This should allow the width to be in device units as opposed to pixels, and it should allow arbitrary widths.  I hope this will be a good way forward!
