### ISSUE TITLE
mglSetGammaTable is too verbose

### ISSUE THREAD

**Issue by dbirman** [justingardner/mgl#6]
Line 76:     disp(sprintf('(mglSetGammaTable) Size of input table (%i) does not match hardwware gamma table size (%i). Interpolating using nearest neighbors - this should make the gamma table act as expected for an %i bit display',inputSize,tableSize,log2(inputSize)));

This output shows up endlessly in task designs that reset the gamma table on every trial, which makes a mess of the console output. Can we add an argument flag ('verbose=0') or something else to suppress the output? I looked at the code, but since it has a table and an expanded form it isn't totally clear what the right way to add this functionality would be.

**Comment by justingardner** [comment]
Ok. Just updated mglSetGammaTable to use oneTimeWarning so it should display once and then not again in the same matlab session.
