### ISSUE TITLE
mglGluDisk, mglGluAnnulus, mglGluPartialAnnulus

### ISSUE THREAD

**Issue by justingardner** [justingardner/mgl#62]
The arguments have changed in these functions, and don't seem to be backwards compatible. Please make the arguments exactly backwards compatible. I understand that some of the arguments are no longer relevant, but just ignore them - so that old code works. Also, it looks like you have new function mglMetalArcs. Perhaps you could put a comment in each of the Glu functions to say that people writing new code should use mglMetalArcs instead.

**Comment by benjamin-heasly** [comment]
I updated these in 4b61f13277e4012aa4bbd3fc3636e90a050e9ba9, I think the parameters now have the same shape as in v2.
