### ISSUE TITLE
mglTestText

### ISSUE THREAD

**Issue by jiwonyeon** [justingardner/mgl#64]
mglTestText crashes with the following error message
---------------------
Output argument "tex" (and possibly others) not assigned a value in the execution
with "mglText" function.

Error in mglTestText (line 135)
mglBltTexture(mglText(jText),[0 50],-1);

**Comment by justingardner** [comment]
This is fixed. But the text is upside down so will leave open until that is resolved.

**Comment by justingardner** [comment]
This is now resolved. Note the strikeout, bold and underline do not work. Also unicode do not work, so will close this but if someone needs those we need to re-implement.
