### ISSUE TITLE
EDF File Warnings

### ISSUE THREAD

**Issue by dbirman** [justingardner/mgl#7]
```
WARNING: EDF FILE MAY BE CORRUPTED. Samples 228098 found without start recording 
WARNING: EDF FILE MAY BE CORRUPTED. Samples 228100 found without start recording 
WARNING: EDF FILE MAY BE CORRUPTED. Samples 228102 found without start recording 
WARNING: EDF FILE MAY BE CORRUPTED. Samples 228104 found without start recording 
WARNING: EDF FILE MAY BE CORRUPTED. Samples 228106 found without start recording 
```

I get these warnings when opening certain eye tracker files. Since I haven't always gotten them I assume this has something to do with the eye tracker and experiemnt not starting/ending at the same time or something similar? Just want to make sure this isn't a real issue.

To reproduce the error load files from Rainbow in dan/data/cohcon/s300/*.edf, which were generated using cohcon.m in grustim

**Comment by justingardner** [comment]
Old issue. I think it's resolved. Closing out.
