### ISSUE TITLE
mglOpen failing 

### ISSUE THREAD

**Issue by cjoynes** [justingardner/mgl#71]
With the VPixx (1920x1200 120Hz refresh) as a second monitor we got the following error. This was replicable across 2 computers and with modified screen parameters (1920x1080, 60Hz refresh rate) 

![mglMetalBug](https://user-images.githubusercontent.com/90854487/175141947-de97fd6f-a031-475a-8e31-27623627f2e3.png)

Attempts to recompile the mex files (using both `mglMakeMetal(1)` and function specific calls i.e. `mglMakeMetal('mglResolution')` ) were not successful in resolving the issue. 

![Screen Shot 2022-06-22 at 1 57 56 PM](https://user-images.githubusercontent.com/90854487/175141948-af42b909-1191-4b2a-ad3e-c66f7acc6eb6.png)

**Comment by justingardner** [comment]
Eli - does this still happen, or can we close this issue?

**Comment by elimerriam** [comment]
This is no longer an issue. We can close...
