### ISSUE TITLE
mglFillOval: oval size is limited

### ISSUE THREAD

**Issue by jenhaensel** [justingardner/mgl#72]
When drawing ovals in mgl metal using mglFillOval, there seems to be an upper limit in terms of displaying oval size. For example, setting the size parameter to [10 10] or [100 100] results in the same-sized oval. Screenshot below illustrates the largest oval size that I can currently achieve.

<img width="396" alt="mglfilloval_snap" src="https://user-images.githubusercontent.com/40855409/176016820-de492429-ab58-49b8-a706-3f87fe957952.png">

**Comment by justingardner** [comment]
Fixed now. Closing.
