### ISSUE TITLE
mglGluAnnulus: inner and outer size of the ring is not in radius but in diameter

### ISSUE THREAD

**Issue by jiwonyeon** [justingardner/mgl#73]
In the description of the metal version mglGluAnnulus as well as in the previous version of the same function, the input values for the isize and osize are radius of the annulus, but what actually the code does is it understands the values as the diameter. To make old scripts compatible to mgl, the inputs should be radius not diameter.

**Comment by justingardner** [comment]
This is fixed now. Closing,
