### ISSUE TITLE
Stencil presented on screen while generating

### ISSUE THREAD

**Issue by jiwonyeon** [justingardner/mgl#75]
Check mglTestStencil.

The stencil doesn't show as circle but oval. Also, when using mglStencilCreateBegin and mglStencilCreateEnd, stencil showed up on the screen while it is not supposed to.

**Comment by justingardner** [comment]
Going to add to this issue thet mglTestStencil also does not seem to draw outer dots.

**Comment by justingardner** [comment]
Resolved.
