### ISSUE TITLE
mglDisplayCursor

### ISSUE THREAD

**Issue by jiwonyeon** [justingardner/mgl#80]
mglDisplayCursor does not properly show the cursor when it's used in callbacks.

**Comment by justingardner** [comment]
This is now fixed. There is a test program called mglTestDisplayCursor which you can use to test. Will only hide/unhide the cursor when the focus is on mglMetal. There may be some way to hide / unhide globally, but this is generally pretty annoying behavior so did not implement (uses the call CGDisplayHideCursor).
