### ISSUE TITLE
mglGluAnnulus and mglMetalArcs not behaving as expected

### ISSUE THREAD

**Issue by jkim6704** [justingardner/mgl#86]
Specifying an outer annulus greater than 10 deg causes the inner annulus to change:

For example, 

mglGluAnnulus(0, 0, 5, 10, [0 .3 0] , 1); mglFlush

and

mglGluAnnulus(0, 0, 5, 12, [0 .3 0] , 1); mglFlush

have different inner annuli, but the same outer annuli

Same for mglMetalArcs

mglMetalArcs([0 0 0]', [1 1 1 1]', [5 10]', [0 2*pi]', [3]); mglFlush
mglMetalArcs([0 0 0]', [1 1 1 1]', [5 12]', [0 2*pi]', [3]); mglFlush

Something is very wrong...

**Comment by justingardner** [comment]
This is fixed now. Closing.
